crypto_dbt:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"

  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_ANALYTICS_DATASET', 'dbt_quants_dev') }}"
      location: "{{ env_var('BQ_LOCATION', 'asia-southeast1') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1

    gke:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_ANALYTICS_DATASET', 'dbt_quants_dev') }}"
      location: "{{ env_var('BQ_LOCATION', 'asia-southeast1') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1