apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: crypto-batch-secrets-gke
  namespace: kestra
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/project-lambda-crypto/secrets/kestra-tiingo-api-key/versions/latest"
        path: "TIINGO_API_KEY"
