# Grant Kestra permissions on GKE

# required rights
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kestra-task-pod-runner
  namespace: kestra
rules:
    # Meaning: Allows the creation of Pods to run temporary jobs, monitoring (watching, listing, getting) 
    # the progress of each Pod, and deleting them to clean up hardware clutter once the Pod is finished.
  - apiGroups: [""]
    resources: ["pods"] # grant permissions to the pod
    verbs: ["get", "create", "delete", "watch", "list"]

    # Sub-resource
  - apiGroups: [""]
    resources: ["pods/log"] # Pod's log suction tube
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"] # pod is used to type and execute commands.
    verbs: ["get", "watch", "create"]
---
# Grant permissions to the service account.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: kestra-task-pod-runner
  namespace: kestra
subjects: # Recipients of rights
  - kind: ServiceAccount
    name: kestra
    namespace: kestra
roleRef: # Assign permissions to objects
  kind: Role
  name: kestra-task-pod-runner
  apiGroup: rbac.authorization.k8s.io
